"""
This script documents how this data was processed and uploaded to HF.

Clean the TinyStories dataset (GPT-4 subset only).

TinyStories (Eldan & Li, 2023) contains ~2.1M short stories generated by GPT-3.5
and GPT-4. We keep only the GPT-4 stories (~470K) since they are higher quality
and more consistent. The cleaning pipeline is:

1. Unicode normalization: curly quotes -> straight quotes, em/en dashes -> hyphens,
   ellipsis character -> "...", stray backslashes removed, double spaces collapsed.
   This keeps the character set small and ASCII-only.

2. Non-ASCII rejection: any story containing characters outside printable ASCII
   (codes 32-127) is discarded, with an exception for newlines (code 10) which
   separate paragraphs within a story. This catches Chinese text, emoji, accented
   characters, and various Unicode garbage that survived GPT-4 generation.

3. Banned character rejection: stories containing any of |<>/`*=_&@~#%[]+() are
   discarded. These almost always indicate formatting artifacts (markdown emphasis,
   HTML tags like <i>, chat templates like <|im_start|>), code contamination, or
   misused punctuation. $ is intentionally allowed (usually correct in context).

4. Minimum length: stories under 100 characters (~15-20 words) are discarded.
   These are typically empty, truncated, or fragmentary.

5. Ending punctuation: stories must end with . ! " or ? to ensure they are
   complete sentences rather than cut-off fragments.

Fetch the raw data first:
    mkdir -p tinystories
    cd tinystories
    wget https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStories_all_data.tar.gz
    tar -xvf TinyStories_all_data.tar.gz
"""

import os
import json
import glob
import random
from collections import Counter

import pyarrow as pa
import pyarrow.parquet as pq

DATA_DIR = "tinystories"

# Characters that indicate a malformed or code-contaminated story.
# $ is intentionally allowed (usually correct usage).
BANNED_CHARS = set('|<>/`*=_&@~#%[]+()')

VALID_ENDINGS = set('.!?"')

# Normalize Unicode punctuation to ASCII equivalents
REPLACEMENTS = [
    ('\\', ''),        # stray backslashes
    ('  ', ' '),       # double spaces
    ('\u2013', '-'),   # en dash
    (' \u2014 ', ' - '),  # spaced em dash
    ('\u2014', ' - '),    # unspaced em dash
    ('\u2026', '...'),    # ellipsis
    ('\u201c', '"'),   # left double curly quote
    ('\u201d', '"'),   # right double curly quote
    ('\u2019', "'"),   # right single curly quote (left curly is culled)
]

# ---- rejection tracking ----
reject_reasons = Counter()

def process_story(text):
    text = text.strip()
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)

    # reject non-ASCII or control characters (allow newline = 10)
    for c in text:
        code = ord(c)
        if code != 10 and (code > 127 or code < 32):
            reject_reasons['non_ascii'] += 1
            return None

    # reject stories with banned characters
    for c in text:
        if c in BANNED_CHARS:
            reject_reasons['banned_char'] += 1
            return None

    # reject very short stories (< 100 chars ~ 15-20 words)
    if len(text) < 100:
        reject_reasons['too_short'] += 1
        return None

    # reject stories that don't end with proper punctuation
    if text[-1] not in VALID_ENDINGS:
        reject_reasons['bad_ending'] += 1
        return None

    return text


# ---- load and clean ----
stories = []
total_raw = 0
total_gpt4 = 0

paths = sorted(glob.glob(f"{DATA_DIR}/*.json"))
for ix, path in enumerate(paths):
    print(f"Processing {ix+1}/{len(paths)}: {path}...")
    with open(path) as f:
        data = json.load(f)
    total_raw += len(data)
    for item in data:
        if item['source'] != 'GPT-4':
            continue
        total_gpt4 += 1
        cleaned = process_story(item['story'])
        if cleaned is not None:
            stories.append(cleaned)

# ---- report stats ----
print(f"Raw stories:       {total_raw:,}")
print(f"GPT-4 stories:     {total_gpt4:,}")
print(f"Survived cleaning: {len(stories):,}")
print(f"Rejected:          {sum(reject_reasons.values()):,}")
print(f"  non_ascii:       {reject_reasons['non_ascii']:,}")
print(f"  banned_char:     {reject_reasons['banned_char']:,}")
print(f"  too_short:       {reject_reasons['too_short']:,}")
print(f"  bad_ending:      {reject_reasons['bad_ending']:,}")

lengths = [len(s) for s in stories]
print(f"\nDoc length (chars): min={min(lengths):,}  max={max(lengths):,}  median={sorted(lengths)[len(lengths)//2]:,}")
print(f"Total chars:       {sum(lengths):,}")

# verify all-ASCII
all_chars = set()
for s in stories:
    all_chars.update(s)
non_ascii = {c for c in all_chars if ord(c) > 127}
assert not non_ascii, f"Non-ASCII chars leaked through: {non_ascii}"
print(f"Unique chars:      {len(all_chars)}")
print(f"Char inventory:    {''.join(sorted(all_chars, key=lambda c: -ord(c) if c.isalpha() else ord(c)))}")

# check for duplicates
n_unique = len(set(stories))
if n_unique < len(stories):
    print(f"\nWARNING: {len(stories) - n_unique:,} duplicate stories found!")
else:
    print(f"Duplicates:        none")

# sample a random story
print(f"\n{'='*60}")
print("Random sample:")
print(random.choice(stories))
print('='*60)

# ---- save as parquet ----
random.shuffle(stories)
out_path = f"{DATA_DIR}/tinystories_gpt4_clean.parquet"
table = pa.Table.from_pydict({"text": stories})
pq.write_table(
    table,
    out_path,
    row_group_size=1024,
    use_dictionary=False,
    compression="zstd",
    compression_level=3,
    write_statistics=False,
)
print(f"\nSaved {len(stories):,} stories to {out_path} ({os.path.getsize(out_path) / 1e6:.1f} MB)")

# ---- save as text ----
out_path = f"{DATA_DIR}/input.txt"
with open(out_path, 'w') as f:
    for story in stories:
        f.write(story + '\n\n')
print(f"\nSaved {len(stories):,} stories to {out_path} ({os.path.getsize(out_path) / 1e6:.1f} MB)")
